site_name: Duon Sire
copyright: © 2022 ebene fünf GmbH
nav:
  - index.md
theme:
  name: duon
repo_url: https://github.com/duon/sire
extra:
  project: Sire
plugins:
  - search
  - macros:
      module_name: docs/main
markdown_extensions:
  - admonition